{
    'name': 'POS Bolivia SIN - Punto de Venta Personalizado',
    'version': '1.0.2',
    'category': 'Point of Sale',
    'summary': 'Punto de venta con facturacion SIN integrada de forma nativa',
    'author': 'Desarrollo propio',
    'depends': ['point_of_sale', 'l10n_bo_electronic_invoice'],
    'data': [
        'security/ir.model.access.csv',
        'views/pos_config_views.xml',
        'views/pos_order_views.xml',
        'views/sin_activity_views.xml',
        'views/sin_config_views.xml',
        'views/sin_offline_queue_views.xml',
        'views/res_company_views.xml',
        'data/pos_data.xml',
        'data/sin_pos_cron.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'l10n_bo_pos_custom/static/src/js/sin_pos.js',
            'l10n_bo_pos_custom/static/src/xml/sin_pos_templates.xml',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}